### ISSUE TITLE
Localization doesn't work properly

### ISSUE THREAD

**Issue by dariuszor** [commercetools/commercetools-sunrise-java-cms#19]
Currently all fetched content is available only in default language.
To fetch content in required other language additional parameter needs to be added here:
https://github.com/commercetools/commercetools-sunrise-java-cms/blob/master/cms-contentful/src/main/java/com/commercetools/sunrise/cms/contentful/ContentfulCmsService.java#L79

@lauraluiz may I create a PR with this change?
When contentful team will merge changes for language fallback I can update it, but currently we require this change.

**Comment by lauraluiz** [comment]
If that fixes the issue, even temporarily, go ahead :)

**Comment by piobra** [comment]
Resolved
