### ISSUE TITLE
document what it acutally does

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-sunrise-java-cms#22]
The READMEs "Module for Sunrise Java with different supported services to use CMS."  does not really help understanding what this does.  

Does it provide the possibilty to place content in category pages?  In product pages?  Is there a route that checks contentful whether there is a page for it (e.g. a new landing page)?  can you edit the home page and how? 

One compact sentence per feature would be very helpful. No details.

**Comment by lauraluiz** [comment]
@nkuehn those details cannot be provided in general. There is a list right below with all supported connectors that links to the documentation of each one. Currently there is only Contentful, but what you are asking should be explained in there, not in the main README.

This Contentful module is a simple adapter that uses the Contentful SDK in a way that can be connected to Sunrise and exchanged with a different CMS if necessary, no magic behind it.

Anyway, I wanted to review the Contentful documentation and improve it if necessary now that it's finished and used.

**Comment by lauraluiz** [comment]
Follow up in here https://github.com/commercetools/commercetools-sunrise-java-cms/issues/23
