### ISSUE TITLE
Update Contentful.java

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java-cms#25]
https://github.com/contentful/contentful.java/releases/tag/java-sdk-7.3.0
which now supports fallback locales

**Comment by lauraluiz** [comment]
Currently the module accepts only the 1st locale and drops the rest.

**Comment by piobra** [comment]
Fallback locales were added to Contentful platform as configuration. They can be set for the project in settings.
They can't, however, be requested on API call as of this release.
Only thing that was added in this skd release for fallback locales was the possibility to get them from fetched models.
