### ISSUE TITLE
consume contentful project credentials from environment parameters

### ISSUE THREAD

**Issue by schleichardt** [commercetools/commercetools-sunrise-java-cms#3]
currently in ContentfulCmsServiceIT the credentials the credentials are static final String literals

see https://github.com/commercetools/commercetools-sunrise-java-cms/pull/2#discussion_r64696287

**Comment by dariuszor** [comment]
@schleichardt https://github.com/commercetools/commercetools-sunrise-java-cms/pull/7

**Comment by schleichardt** [comment]
thanks
