### ISSUE TITLE
Check leaked connection error

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java-cms#35]
This topic has already been covered but no conclusion stablished. Let's look at it again.
The HTTP client used by Contentful integration often prints:

```
A connection to https://cdn.contentful.com/ was leaked. Did you forget to close a response body?
```

**Comment by dariuszor** [comment]
@lauraluiz it was a mistake on contentful sdk side. Response bode wasn't close in error case. It was fixed int his PR: https://github.com/contentful/contentful.java/pull/143, so updating to newer sdk version should fix it. Cheers!

**Comment by lauraluiz** [comment]
@dariuszor thanks a lot! I'm very glad that you have such a good memory (unlike me 😄 ).
It's also good to notice that the SDK was quite outdated :)
