### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-java-cms#5]
Currently people won't be able to catch any exception from the connectors (for each connector a different exception will be thrown). 
- [x] Create `CmsServiceException`
- [ ] Then wrap any Contentful exception in ours
- [ ] Check in the Unauthorized IT if our exception is the cause with `.hasCauseInstanceOf(CmsServiceException.class)`
- [ ] Put also the missing exception documentation in both `CmsService` and `ContentfulCmsService`, the exception should be explained in `@result` and not in the typical `@thrown`, since it is found inside the CompletionStage, look for inspiration: https://github.com/commercetools/commercetools-sunrise-java-email/blob/master/email-common/src/main/java/io/commercetools/sunrise/email/EmailSender.java#L77-L80.

**Comment by piobra** [comment]
Resolved
